language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development

before_script: 
  - cd project  # enter Maven root directory
  - ls -la # print the contents of the current working directory

script: 
  - mvn clean package